package hackerrouter.mineshaftforcer.simulation;

public enum CorridorEventType {
	GENERATE_MAYBE_BOX_ROLL,
	SUPPORT_CHECK,
	SUPPORT_STYLE_ROLL,
	SUPPORT_TORCH_ROLL,
	COBWEB_INTERIOR_SKIPPED,
	COBWEB_ROLL,
	MINECART_CHANCE_ROLL,
	MINECART_SACRIFICED,
	MINECART_LOOT_SEED,
	SPIDER_SPAWNER_ROLL,
	RAIL_ROLL
}
